name: Auto merge main to live after a PR is closed

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  update-cms-master:
    name: Merge main into live after a PR is merged
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: merge
        uses: richard-scott/automerger-action@latest
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source: 'main'
          target: 'live'
          message: "Merge to live from main"